export const TECH_SKILLS = {
  languages: [
    "JavaScript",
    "TypeScript",
    "Python",
    "Java",
    "C++",
    "C#",
    "Go",
    "Rust",
    "Swift",
    "Kotlin",
    "PHP",
    "Ruby",
    "SQL",
    "HTML",
    "CSS",
    "R",
    "MATLAB",
    "Scala",
    "Perl",
    "Haskell",
    "Dart",
    "Objective-C",
    "C",
    "Shell",
    "Bash",
    "PowerShell",
    "Groovy",
    "Clojure",
    "Elixir",
    "Erlang",
    "F#",
    "Fortran",
    "COBOL",
    "Lisp",
    "Prolog",
    "Solidity",
  ],
  frameworks: [
    "React",
    "Angular",
    "Vue",
    "Next.js",
    "Nuxt.js",
    "Express",
    "Django",
    "Flask",
    "Spring Boot",
    "Laravel",
    "Ruby on Rails",
    "ASP.NET",
    "FastAPI",
    "Svelte",
    "Ember",
    "Backbone",
    "Meteor",
    "Koa",
    "NestJS",
    "Quarkus",
    "Micronaut",
    "Play Framework",
    "Symfony",
    "CodeIgniter",
    "CakePHP",
    "Zend",
    "Phoenix",
    "Gatsby",
    "Remix",
    "SolidJS",
    "Alpine.js",
    "Lit",
    "Preact",
    "Tailwind CSS",
    "Bootstrap",
    "Material UI",
    "Chakra UI",
    "Ant Design",
    "Bulma",
    "Foundation",
  ],
  databases: [
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "SQLite",
    "Oracle",
    "Cassandra",
    "DynamoDB",
    "Firebase",
    "Elasticsearch",
    "MariaDB",
    "CouchDB",
    "Neo4j",
    "InfluxDB",
    "ClickHouse",
    "CockroachDB",
    "FaunaDB",
    "Memcached",
    "Presto",
    "Snowflake",
    "BigQuery",
    "Redshift",
    "Google Cloud Spanner",
    "Amazon Aurora",
    "Pinecone",
    "Milvus",
    "ChromaDB",
    "Weaviate",
    "Qdrant",
    "pgvector",
    "Marqo",
    "Faiss",
    "ScaNN",
    "Databricks",
    "Delta Lake",
    "Apache Iceberg",
    "Snowflake Snowpark",
    "Feast Feature Store",
    "BigchainDB",
    "IPFS",
    "OrbitDB",
    "GunDB",
    "Amazon QLDB",
    "Supabase",
    "SurrealDB",
    "EdgeDB",
    "YugabyteDB",
    "ScyllaDB",
  ],
  cloud: [
    "AWS",
    "Azure",
    "Google Cloud",
    "GCP",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Ansible",
    "Jenkins",
    "CircleCI",
    "GitHub Actions",
    "GitLab CI",
    "Travis CI",
    "Bamboo",
    "Vagrant",
    "Packer",
    "Helm",
    "Istio",
    "Prometheus",
    "Grafana",
    "ELK Stack",
    "Splunk",
    "New Relic",
    "Datadog",
    "OpenStack",
    "DigitalOcean",
    "Heroku",
    "Netlify",
    "Vercel",
    "Cloudflare",
  ],
  tools: [
    "Git",
    "GitHub",
    "GitLab",
    "Jira",
    "Confluence",
    "Postman",
    "Figma",
    "Webpack",
    "Vite",
    "Babel",
    "NPM",
    "Yarn",
    "PNPM",
    "Slack",
    "Trello",
    "Asana",
    "Notion",
    "VS Code",
    "IntelliJ IDEA",
    "PyCharm",
    "WebStorm",
    "Docker Desktop",
    "Insomnia",
    "Swagger",
    "Storybook",
    "Jest",
    "Cypress",
    "Selenium",
    "Puppeteer",
    "Playwright",
    "Mocha",
    "Chai",
    "Enzyme",
    "React Testing Library",
  ],
  concepts: [
    "REST API",
    "GraphQL",
    "Microservices",
    "Serverless",
    "CI/CD",
    "Agile",
    "Scrum",
    "TDD",
    "Unit Testing",
    "System Design",
    "Object Oriented Programming",
    "OOP",
    "Functional Programming",
    "Reactive Programming",
    "Event-Driven Architecture",
    "SOA",
    "MVC",
    "MVVM",
    "Clean Architecture",
    "Domain Driven Design",
    "DDD",
    "SOLID Principles",
    "Design Patterns",
    "Security",
    "OAuth",
    "JWT",
    "WebSockets",
    "WebRTC",
    "PWA",
    "SEO",
    "Accessibility",
    "A11y",
    "Internationalization",
    "i18n",
    "Smart Contracts",
    "DeFi (Decentralized Finance)",
    "DApps",
    "Cryptography",
    "Consensus Algorithms",
    "Ethereum Virtual Machine (EVM)",
    "Zero-Knowledge Proofs",
    "Layer 2 Solutions",
  ],
  dataScience: [
    "Pandas",
    "NumPy",
    "Scikit-learn",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Matplotlib",
    "Seaborn",
    "Plotly",
    "NLTK",
    "Spacy",
    "OpenCV",
    "Spark",
    "Hadoop",
    "Kafka",
    "Airflow",
    "Tableau",
    "Power BI",
    "D3.js",
    "Statistics",
    "Linear Algebra",
    "Calculus",
    "Probability",
    "Big Data",
    "Data Mining",
    "Data Engineering",
    "Generative AI",
    "LLMs",
    "RAG (Retrieval-Augmented Generation)",
    "Prompt Engineering",
    "Fine-Tuning",
    "LangChain",
    "LlamaIndex",
    "Hugging Face",
    "MLOps",
    "Weights & Biases",
    "MLflow",
    "Vertex AI",
    "SageMaker",
    "Vector Search",
    "Deep Learning",
    "NLP",
  ],
  mobile: [
    "React Native",
    "Flutter",
    "Ionic",
    "Xamarin",
    "Cordova",
    "PhoneGap",
    "NativeScript",
    "SwiftUI",
    "Jetpack Compose",
    "Android SDK",
    "iOS SDK",
    "Xcode",
    "Android Studio",
  ],
};

export const JOB_ROLES = [
  {
    title: "Frontend Developer",
    keywords: [
      "React",
      "Vue",
      "Angular",
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "Frontend",
      "UI/UX",
      "Tailwind",
      "SASS",
      "Responsive Design",
      "Web Performance",
    ],
  },
  {
    title: "Backend Developer",
    keywords: [
      "Node.js",
      "Express",
      "Python",
      "Django",
      "Flask",
      "Java",
      "Spring Boot",
      "Backend",
      "API",
      "SQL",
      "PostgreSQL",
      "MongoDB",
      "Microservices",
      "Caching",
    ],
  },
  {
    title: "Fullstack Developer",
    keywords: [
      "React",
      "Node.js",
      "Fullstack",
      "MERN",
      "PERN",
      "TypeScript",
      "SQL",
      "NoSQL",
      "DevOps",
      "Architecture",
    ],
  },
  {
    title: "Data Scientist",
    keywords: [
      "Python",
      "R",
      "Machine Learning",
      "Data Science",
      "Pandas",
      "NumPy",
      "Scikit-learn",
      "TensorFlow",
      "PyTorch",
      "Statistics",
      "Deep Learning",
      "NLP",
    ],
  },
  {
    title: "DevOps Engineer",
    keywords: [
      "AWS",
      "Azure",
      "Docker",
      "Kubernetes",
      "CI/CD",
      "Terraform",
      "Jenkins",
      "Linux",
      "Automation",
      "Cloud",
      "Monitoring",
      "Infrastructure as Code",
    ],
  },
  {
    title: "Mobile Developer",
    keywords: [
      "React Native",
      "Flutter",
      "Swift",
      "Kotlin",
      "Android",
      "iOS",
      "Mobile App",
      "Mobile Development",
      "App Store",
      "Play Store",
    ],
  },
  {
    title: "Data Engineer",
    keywords: [
      "Spark",
      "Hadoop",
      "Kafka",
      "Airflow",
      "ETL",
      "Data Pipeline",
      "SQL",
      "Python",
      "Big Data",
      "Data Warehousing",
    ],
  },
  {
    title: "Security Engineer",
    keywords: [
      "Cybersecurity",
      "Penetration Testing",
      "Encryption",
      "OAuth",
      "Security Audit",
      "Firewall",
      "Vulnerability Assessment",
      "Identity Management",
    ],
  },
  {
    title: "Cloud Architect",
    keywords: [
      "AWS",
      "Azure",
      "GCP",
      "Cloud Strategy",
      "Serverless",
      "Scalability",
      "High Availability",
      "Cloud Migration",
    ],
  },
  {
    title: "QA Engineer",
    keywords: [
      "Testing",
      "Automation",
      "Selenium",
      "Jest",
      "Cypress",
      "Quality Assurance",
      "Unit Testing",
      "Integration Testing",
      "Bug Tracking",
    ],
  },
];

export const RESUME_SECTIONS = [
  "Experience",
  "Education",
  "Projects",
  "Skills",
  "Summary",
  "Contact",
  "Certifications",
  "Awards",
  "Languages",
  "Interests",
  "Volunteer",
  "Publications",
  "Patents",
  "References",
];
